<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INDPRFTCPL1690" failures="1" tests="3" name="ErrorValidation_Tests" time="36.215" errors="0" timestamp="2024-08-06T14:04:43 IST">
  <testcase classname="Perficient.SeleniumFrameworkDesign.LoginError" name="loginErrorValidation" time="1.173"/>
  <testcase classname="Perficient.SeleniumFrameworkDesign.LoginError" name="productErrorValidation" time="13.682">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="Perficient.SeleniumFrameworkDesign.LoginError" name="productErrorValidation" time="13.724">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Perficient.SeleniumFrameworkDesign.LoginError.productErrorValidation(LoginError.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- ErrorValidation_Tests -->
